services:
  mongodb:
    image: mongo:latest
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - 27017:27017

  odyssey:
    image: odyssey:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
